### ISSUE TITLE
[Tema] Python Pandas

### ISSUE THREAD

**Issue by tramuntanal** [pygrn/xerrades#12]
### Introducció a Pandas
http://pandas.pydata.org/

Tipus de la proposta:
- [X] Vull proposar un tema interessant
- [ ] Vull fer una xerrada

Llibreria super potent de maneig de dades. Estaria bé si algú (@victormartingarcia) pot fer una intro als temes bàsics.

Duració estimada: ???
Local: Podria oferir les oficines de CodiTramuntana si som pocs :smile: 

TAGS: `data science`

**Comment by victormartingarcia** [comment]
Sí, puc fer una petita intro a pandas 💃

**Comment by XaviTorello** [comment]
Bona idea @tramuntanal 👍  Sobre els llocs, els estem tractant a https://github.com/pygrn/xerrades/issues/1; si t'animes contesta la issue afegint les dades del lloc

@victormartingarcia si t'animes a fer-la obre una nova issue (fent referència a aquesta) please!
