### ISSUE TITLE
[Xerrada][Mini] Introducció a Pandas

### ISSUE THREAD

**Issue by victormartingarcia** [pygrn/xerrades#13]
### Introducció a Pandas

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [X] Vull fer una xerrada

A [proposta de l'Oliver](https://github.com/pygrn/ideesxerrades/issues/12) m'ofereixo a fer una introducció pràctica sobre la llibrería [Pandas](http://pandas.pydata.org/)

Pandas es una llibrería per a l'anàlisis de dades, molt utilitzada en temes de data-science

Duració estimada: 30m

TAGS: `pandas, data-science, jupyter, notebook`

**Comment by XaviTorello** [comment]
Genial, gràcies @victormartingarcia

**Comment by tramuntanal** [comment]
+1

**Comment by XaviTorello** [comment]
Tanquem issue! Seleccionada per la sessió del dia 12/07/17

Gràcies @victormartingarcia

**Comment by TeresaO** [comment]
Si al final se hace esta Xerrada, a mi me gustaría escucharla.
¿cómo puedo estar informada sobre cuándo, cómo y dónde comentaréis este tema?

**Comment by victormartingarcia** [comment]
@TeresaO la intro sobre pandas fue ayer en Girona, dentro del 1r meetup del grupo [PyGrn](https://www.meetup.com/PythonGirona/events/241597088/)

Los eventos normalmente se anuncian con unos días de antelación en el grupo de [meetup PythonGirona](https://www.meetup.com/PythonGirona/) y en el canal de Telegram https://t.me/pygrn

Puedes ver los slides y el código (formato notebook) de mi charla en el repo https://github.com/victormartingarcia/2017-pyGrn-intropandas
