### ISSUE TITLE
[Xerrada] No tot és programar! Documentar, testejar, integrar i desplegar

### ISSUE THREAD

**Issue by ecarreras** [pygrn/xerrades#15]
### No tot és programar! Documentar, testejar, integrar i desplegar

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Tothom sap que el més divertit és programar! però no ha de ser l'única cosa en que en hem de centrar.
En aquesta xerrada vull explicar el que envolta un codi, que no sempre hi és però seria bó que hi fos.

La xerrada tindria 4 blocs:

- Documentació de projectes (mkdocs i sphinx)
- Testing: Metodologia TDD i clàssica i eines
- Integració: Concepte
- Desplegament: Concepte i algunes eines
- Monitoritzar un cop desplegat

Duració estimada 1h

TAGS: `Ecosistema, Testing, Documentació, Integració, Desplegament`

**Comment by jbagot** [comment]
Molt bona! Super interessant!

**Comment by XaviTorello** [comment]
Genial @ecarreras 👏 , la vinculo a #4!

**Comment by victormartingarcia** [comment]
+1

**Comment by XaviTorello** [comment]
Tanquem issue! Seleccionada per la sessió del dia 13/09/17

Gràcies @ecarreras

**Comment by abusquets** [comment]
@ecarreras penjaràs la presentació?

**Comment by ecarreras** [comment]
La presentació es pot trobar a https://ecarreras.github.io/xerrada-pygrn-no-tot-es-programar/ i la font al repositori Git https://github.com/ecarreras/xerrada-pygrn-no-tot-es-programar
