### ISSUE TITLE
[Xerrada] Django

### ISSUE THREAD

**Issue by manelclos** [pygrn/xerrades#19]
### Framework Web Django

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Les possibilitats del framework django son infinites i pot solucionar escenaris complexes. Seria interessant veure el bootstraping per perdre-li la por amb una sessió "hands on", i també alguna presentació de possibilitats, incloent llibreries que s'integren amb Django.

Si hi ha interés i algú més s'apunta a fer-ho, jo faria part del taller o xerrada.

1h Taller
1-2 hores Presentació

TAGS: `django, web`

**Comment by XaviTorello** [comment]
@francescarpi no t'animes? 😄

**Comment by francescarpi** [comment]
Bones!
Hi tant que sí. Pots comptar-hi :)

**Comment by XaviTorello** [comment]
Xerrada integrada a #24, tanquem issue.

@manelclos posa't en contacte amb nosaltres per encarar-ho tot plegat 🙏

**Comment by manelclos** [comment]
@XaviTorello i tant, com?

**Comment by XaviTorello** [comment]
Tenim un grup a Telegram, si pots entra i ho parlem allà :thumbsup:

https://t.me/pygrn
