### ISSUE TITLE
[Xerrada] Ansible

### ISSUE THREAD

**Issue by manelclos** [pygrn/xerrades#20]
### Ansible per DevOps

Tipus de la proposta:
- [X] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Ansible permet automatitzar i alhora documentar el desplagament de sistemes i aplicacions. Els escenaris són molts, des de controlar màquines de AWS, a simples desplegaments d'aplicacions o webs estàtiques. Com tot framework gran, costa entrar en els conceptes i apareixen molts dubtes, seria bo fer un taller per veure possibilitats i perdre-li la por.

Si hi ha interés i algú més s'apunta a fer-ho, jo faria part del taller o xerrada.

1h Taller
1-2 hores Presentació

TAGS: `Ansible, DevOps`

**Comment by francescpuig7** [comment]
Em sembla molt interessant, tinc ganes d'aprendre'n!

:cake: de part d'en @jaumef

**Comment by guilleJB** [comment]
:+1:

**Comment by XaviTorello** [comment]
Genial, gràcies @manelclos! 🍫 

Algú s'anima a preparar-ho conjuntament amb en Manel? 🙏

**Comment by manelclos** [comment]
Xerra feta ahir per en Jaume
