### ISSUE TITLE
[XerradaMini] Com empaquetar i publicar paquets python

### ISSUE THREAD

**Issue by ecarreras** [pygrn/xerrades#21]
### Títol de la proposta

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Tots programem amb Python però quants publiquem els nostres paquets al Pypi?
La idea és ensenyar la forma bàsica d'empaquetar i publicar paquets.

- Estructura `setup.py`
- Publicar Pypi
- Integració comandes executables (amb click)
- Extensió amb `entry_points`

20min. Si es veu interessant es pot fer format taller

TAGS: `setup, Pypi, paquets`

Xerrada Feta el 31/03/2022, Slides: https://ecarreras.github.io/xerrada-pygrn-packaging

**Comment by jbagot** [comment]
També s'hi podrien incloure llibreries com Flit o Poetry

**Comment by XaviTorello** [comment]
`Poetry` està agafant bastanta força, potser seria interessant convertir-la en una sessió "normal" on tractar empaquetat, publicació, entorns virtuals i resolució de dependències.

Què en penseu @ecarreras @jbagot?

La fem online o esperem a que ens puguem tornar a trobar?

**Comment by ecarreras** [comment]
A mi em sembla perfecte afegir-hi més coses 💪 jo no les conec tant però si algú vol afegir-hi afegir-hi aquesta part molaria.

La meva idea era explicar el setup.py els iter_packages per fer plugins, etc. Però estaria molt bé fer la part de la gestió de dependències.

Fins i tot les diferents maneres de gestionar entorns, pyenv, virtualenv, venc, ...

**Comment by ecarreras** [comment]
Acabo de llegir aquest article https://frostming.com/2021/01-22/introducing-pdm/ on es parla d'una altra eina PDM que intenta utilitzar la idea del `node_modules` als projectes python

**Comment by manelclos** [comment]
@ecarreras fa molt bona pinta, a veure si no pasa com amb `pipenv` 🤞

**Comment by ecarreras** [comment]
Xerrada feta el 31/02/2022
