### ISSUE TITLE
[Xerrada] Django APP&API + React client

### ISSUE THREAD

**Issue by XaviTorello** [pygrn/xerrades#24]
### Django APP&API + React client 

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [X] Vull fer una xerrada

Relacionat amb les dues propostes de xerrada rebudes vinculades al món web ("Intro a React" #14 i "Django" 19) ens hem plantejat fer un petit "popurrí" i integrar-ho tot plegat en una única sessió.

Ho acabarem de detallar en breu un cop ho haguem posat tot en comú

Duració estimada 60 - 90'

Sessió per @manelclos i @francescarpi

TAGS: web, django, react, redux

**Comment by francescarpi** [comment]
Ja hi estem treballant :)

**Comment by XaviTorello** [comment]
Xerrada seleccionada per la propera sessió (dia 15/11).

Gràcies @manelclos i @francescarpi 🍫

**Comment by manelclos** [comment]
@XaviTorello ja he publicat el codi, i al README he posat instruccions per instal·lar i enllaç a la presentació. Falta res més?

**Comment by XaviTorello** [comment]
Genial Manel!

Gràcies @manelclos i @francescarpi per la xerrada d'ahir, va estar molt bé :+1:

**Comment by francescarpi** [comment]
Afegeixo enllaç de la presentació:
https://docs.google.com/presentation/d/1F4_CYdHbXwP-eVR6CBtoAXceZLplfiKbBGK0-xwRTyk/edit?usp=sharing

**Comment by XaviTorello** [comment]
Després miro d'actualitzar les entrades a la llista de xerrades per a que apunti al vostre repo i a les vostres presentacions.

Gràcies @francescarpi i @manelclos
