### ISSUE TITLE
[Xerrada] Elastic Search amb python

### ISSUE THREAD

**Issue by Xevib** [pygrn/xerrades#26]
### Títol de la proposta

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Elastic Search es un motor de cerca molt potent que podem usar des de Python. En aquesta xerrada vull fer una introduccio a Elastic search i com integrar-ho amb Python.

Duració estimada

TAGS: `Elastic search, cerca`

**Comment by XaviTorello** [comment]
:clap: :clap: :clap:

**Comment by XaviTorello** [comment]
Seleccionada per la sessió del 17/01/18.

Gràcies @Xevib  🍻
