### ISSUE TITLE
[Xerrades] Només puc oferir birres

### ISSUE THREAD

**Issue by mamutera** [pygrn/xerrades#28]
Bon dia,
Sóc en Màrius Colomer, sóc el tio que a les xerrades es posa a primera fila però no diu res. Bàsicament escric la issue pq l'altre dia es va fer una crida a col·laborar al grup i el problema és que no tinc ni ****** idea de programar. Vaig començar a apendre python fa uns mesos per curiositat personal i el nivell dels assistents és massa alt pq pugui col·laborar de cap manera.

Per això he pensat que el pròxim cop que es quedi i hi hagi birres pel mig, tant els organitzadors com els ponents tenen les rondes pagades.

**Comment by XaviTorello** [comment]
M'ho apunto :smiling_imp:  heheheh

Fora conyes, segur que podem trobar la manera de col·laborar :+1: 

Gràcies @mamutera :beers:

**Comment by XaviTorello** [comment]
Tanquem issue; tot i això et prenem la paraula @mamutera  :)

Si t'animes a preparar alguna xerrada sobre el que t'apassioni avisa'ns, segur que pots trobar un tema del món pythoner o techie en general per introduïr-nos en una sessió :muscle: 

:beers: :beers: :beers:
