### ISSUE TITLE
Introducció a Vue.js (+ Taller)

### ISSUE THREAD

**Issue by manelclos** [pygrn/xerrades#34]
### Introducció a Vue.js (+ Taller)

Tipus de la proposta:
- [  ] Vull proposar un tema interessant
- [X] Vull fer una xerrada

Explicar Vue.js a partir de la xerrada que ja va fer en Francesc sobre React. Per completar, ja que react consumia una API feta en Django, es podria fer la mateixa API en Flask per consumir des de Vue.js.

30 minuts d'explicació i llavors el taller.

TAGS: `vuejs, flask`

**Comment by ecarreras** [comment]
@manelclos jo si vols m'animo a fer la part de Flask!

**Comment by manelclos** [comment]
Contractat!

**Comment by XaviTorello** [comment]
Gràcies nanos!! :beers:

**Comment by XaviTorello** [comment]
Xerrada feta el 13/12/2018, gràcies @manelclos! Tanquem issue i referenciem continguts al repo base
