### ISSUE TITLE
[Xerrada] Introducció a locust

### ISSUE THREAD

**Issue by ecarreras** [pygrn/xerrades#35]
### Tests de càrrega pels nostres Serveis

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Moltes vegades desenvolupem serveis i fem tests del codi, de la interfície però no testegem quina capacitat de càrrega pot aguantar i com es comporta amb aquesta càrrega.

Amb l'eina [Locust](https://locust.io/) ens permet fer simulacions de càrrega i comportaments d'usuari amb Python.

- Què és una eina de càrrega
- Quines hi ha
- Exemples de simulacions d'usuaris
- Integració amb el CI.

:timer_clock: 1h30m

TAGS: `locust, load testing, services testing`

**Comment by manelclos** [comment]
+1

**Comment by abusquets** [comment]
Nosaltres fem servir jmeter per la funcionalitat d'execució distribuïda a través de nodes.
El client diu que executar un plan en una mateixa màquina no és real.
Es pot fer això amb el locust?

**Comment by ecarreras** [comment]
@abusquets sí, [locust](https://locust.io/) permet fer simulacions amb [nodes distribuits](https://docs.locust.io/en/stable/running-locust-distributed.html).

No he utilitzat [JMeter](https://jmeter.apache.org/) però suposo que té moltes més funcionalitats, potser puc mirar de fer una comparativa

**Comment by victormartingarcia** [comment]
molt interessant @ecarreras !

**Comment by abusquets** [comment]
Ara ho he vist, viam els informes

**Comment by XaviTorello** [comment]
Ouuu yeah @ecarreras, pinta :beer: molt bé!

**Comment by XaviTorello** [comment]
Xerrada feta el 27/09/2018, gràcies @ecarreras. Si vols podem linkar-hi les slides i continguts
