### ISSUE TITLE
[Xerrada] Back:(Python + GraphQL) -> Front:(React + StyledComponents)

### ISSUE THREAD

**Issue by d-asensio** [pygrn/xerrades#36]
### Tipus de la proposta:
- [x] Vull proposar un tema interessant
- [x] Vull fer una xerrada

### Proposta
No tinc una idea clara de com orientar-ho, però m'agradaria fer una xerrada sobre [GraphQL](https://graphql.org/learn/), [React](https://reactjs.org/) i [styled-components](https://www.styled-components.com/).

El cas és que a la feina estem fent servir aquestes tecnologies i trobo que seria genial compartir la nostra experiència.

L'únic inconvenient és que de Python no en tinc gaire idea, nosaltres fem servir un backend fet en PHP i Node.js, així que segurament necessiti una mica d'ajuda per fer la xerrada, sobretot amb la part de Python i [Graphene](http://graphene-python.org/). Però bé, així també em servirà per endinsar-me en el "mundillo" del Python, que fa temps que li tinc ganes. 👍

### Una mica més de context
Crec que les parts que poden ser més interessants en aquesta xerrada són la de [styled-components](https://www.styled-components.com/) i [GraphQL](https://graphql.org/learn/), així que faré un breu resum de que són per a aquells que no les coneixeu:

- __GraphQL:__ És un llenguatge de queries per fer API's. Bàsicament aspira a reemplaçar les API's REST en els pròxims anys. Sembla molt agosarat, però us asseguro que després de fer-ho servir durant un temps, no m'imagino tornant a fer servir una API REST per consumir dades des del front-end.

##### API REST
```http
GET /spaceShips/3?fields=name,pilot,releaseDate
GET /spaceShips/3/visitedPlanets/?fields=name,coordinates
```

##### GQL
```gql
{
  SpaceShip(id: 3) {
    name
    pilot
    releaseDate
    visitedPlanets {
      name
      coordinates {
        x
        y
      }
    }
  }
}
```

- __StyledComponents:__ Crec que la més popular de les llibreries per fer CSS-in-JS, és a dir, escriure el CSS directament des de JavaScritpt 😨, al principi sembla una mica incòmode, però la veritat és que quan t'acostumes a la sintaxi, és un goig!

Espero el vostre feedback!

Durada: ~2h

TAGS: `PYTHON, GRAPHQL, REACT, STYLED-COMPONENTS, RESTWILLDIE`

**Comment by ecarreras** [comment]
Molt interessant!!! 👏👏👏👏

**Comment by neich** [comment]
+1

**Comment by victormartingarcia** [comment]
+1 

Super interessat!! 😀

**Comment by XaviTorello** [comment]
Molt bona!!! Fa massa dies que tinc pendent jugar una mica amb GraphQL, @d-asensio si vols podem investigar-ho plegats per preparar la sessió :)

**Comment by d-asensio** [comment]
@XaviTorello doncs estaria molt bé! Si vols, envia'm un e-mail i mirem de posar-nos d'acord. 😉

Merci!

**Comment by tramuntanal** [comment]
Seria interessant comparar com ho gestiona Ruby? potser podriem fer una petita part de la sessió des de CodiTramuntana si acordem fer una "mini-demo" i veure com queda en els dos llenguatges? com ho veieu?

**Comment by d-asensio** [comment]
@tramuntanal Pot estar genial! Ho feu servir també? Com a punt de partida he vist que a [How to GraphQL](https://www.howtographql.com/) tenen un [tutorial orientat a Ruby](https://www.howtographql.com/graphql-ruby/0-introduction/) molt interessant.

**Comment by XaviTorello** [comment]
Parlem per gitter si vols @d-asensio, a viam si treiem algo txulo :yum:

**Comment by tramuntanal** [comment]
Ho utilitzem en 1 projecte, no és que en siguem experts ni molt menys, però ens hi estem posant. Encara no tinc clar si aporta tants beneficis respecte a uns WS clàssics.

**Comment by warlock** [comment]
Ho utilitzo activament amb Node.js i en el front l'utilizo amb React, React-Native i Vue. Varem estar parlant a l'última trobada que podria ser interessant veure com es treballa en diferents llenguatges.

El llenguatge de query és molt simple. Crec que es podria fer una introducció rapida de les query basiques i ensenyar a preparar l’esquema.

I llavors estaria bé que diverses persones en diferents llenguatges fessin cinc cèntims de la implementació als servidors.

No parlo d’ensenyar a utilizar ORM. Parlo de quines llibreries i dependencies s'utilitza, com estructurar les dades un usuari que l’utilitza activament i mostrar com es configuren alguns resolvers.

Referent al upload d’arxius, gestió del token i a les subscripcions potser no ho posaria en aquesta xerrada.
Em refereixo a que com a molt jugarem amb el BACK + el playground.

Crec que no es una xerrada molt extensa si obviem el tema dels ORM i se que no hi ha molt temps en un sol dia, crec que podria ser força dinamic. I m’agrada veure com treballen els professionals de diferents llenguatges i com es pot resoldre el mateix problema desde diferents punts de vista.
Que opineu?

**Comment by XaviTorello** [comment]
Bona idea @warlock! Vàrem estar comentant amb en @d-asensio com encarar la sessió, i molt probablement fem una sessió específica on puguem conèixer tots plegats què és `GraphQL` servit des de `Python` amb un frontal fet en `React` (+styled).

Normalment fem sessions curtes de màxim 50' (excepte quan es tracta de tallers) i després fem una ronda de vàries *lightning talks* (max 5'), depenent de qui s'animi.

Potser podríem aprofitar aquesta mateixa sessió per -via xerrades llamp- complementar la xerrada base de `Python` + `GraphQL`, i durant el sopar poder comentar experiències plegats.

Si t'animes podries preparar una llamp per explicar la teva experiència amb QQL sobre `node.js`!!! :eyes:

**Comment by warlock** [comment]
Ok. Compteu amb mi.

**Comment by XaviTorello** [comment]
@d-asensio quan puguis ens confirmes el repo on trobar les slides i recursos de la xerrada plz?

Si vols, si no en tens cap preparat pots pujar-ho a https://github.com/pygrn/graphql_flask

Related to #50 

Thxs!! :beers:
