### ISSUE TITLE
Xerrada: Penetration-testing a través de python

### ISSUE THREAD

**Issue by paumnoz** [pygrn/xerrades#43]
## Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [X] Vull fer una xerrada

## Descripció:

En aquesta xerrada es preten exposar tot el procediment a seguir durant un procés d'auditoria de seguretat estil "pen-testing" des d'una perspectiva 100% python. Es presentarà metodologia i eines concretes desenvolupades en python, explicant part del seu funcionament intern per entendre millor el procés.

Duració estimada: 45 minuts

TAGS: `hacking, pentesting, ciberseguretat, eines`

**Comment by jbagot** [comment]
Ho trobo molt interessant. Per mi quan vulguis :)

**Comment by XaviTorello** [comment]
Xerrada feta el 15/11/2018 durant la sessió 10! @tyger99 si vols podem linkar-te el repo amb les slides i continguts
