### ISSUE TITLE
Scientific Python

### ISSUE THREAD

**Issue by efarres** [pygrn/xerrades#48]
### Scientific Python - SciPy 

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

## Descripció.
En aquesta xerrada voldria presentar un conjunt d'eines que ens faciliten la comprensió dels nostre entorn, i que ens permeten el desenvolupament de solucions. 

L'aproximació a la xerrada no la faria com a programador de Python, sinó que la faria com a científic (físic/electrònic) que utilitzà Python con una eina molt útil en el desenvolupament d'instruments de mesura.

Duració estimada.
60 minuts.

Elements a presentar:
- [SciPy](https://www.scipy.org).
   - NumPy.
Tot es tracta de multiplicar i sumar, **com tractar vectors i matrius**.
   - SciPy Library.
No cal reinventar la roda, **com implementar els coneixements**.
   - Matplotlib.
Un cop fet, representem-ho, **fem més que gràfiques**
   - IPython.
No sabem encara on anem, **interactuem**.
   - Pandas (veure xerrada [12/07/2017 - PyGRN#1 Scrapy + Pandas (https://github.com/pygrn/xerrades/blob/master/xerrades/2017/20170712)).
**Donem estructura a les dades**.
- [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) Interface web per [Project Jupyter](https://jupyter.org/).
Deixem-ho tot documentat, **millor, documentem mentre anem fent**.

TAGS: `SciPy, JupyterLab, Scientific Computing, Instrumentació, Anàlisi de dades, documentació`

**Comment by XaviTorello** [comment]
Genial @efarres, fa molt bona pinta! Gràcies! :beers:

**Comment by manelclos** [comment]
I tant! Mentre llegia la descripció ja m'hi he vist a la xerrada! +10 :)

**Comment by victormartingarcia** [comment]
+1E6 ! ;)

**Comment by XaviTorello** [comment]
Seleccionada per la propera trobada, gràcies @efarres!
