### ISSUE TITLE
[Xerrada] Scrapy

### ISSUE THREAD

**Issue by jbagot** [pygrn/xerrades#5]
### Scrapy

- [x] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Fa anys que treballo amb scrapy que és el framework per excel·lència per fer web crawling. Si és del vostre interès puc prepara-me una xerrada i exemples per introduir-vos en el tema.

Puc parlar del framework, Xpath, Tor, Requests, etc. El que us interessi a vosaltres.

A part, he adaptat el scrapy amb Flask, així que tinc una API que scrapeja, també podem parlar d'això. Ja que va relacionat amb una altre "issue".

**Comment by XaviTorello** [comment]
Genial!!! Moltes gràcies @jbagot

**Comment by guilleJB** [comment]
:+1:

**Comment by marcfp** [comment]
😉dpm!! Merci profe!!! 😘😘😘😘😂😂😂😂😂😂😂😂😂😂😂

**Comment by victormartingarcia** [comment]
+1

**Comment by jccamel** [comment]
+1

**Comment by marcfp** [comment]
+1

On 5 de juliol de 2017 23:49:46 CEST, Juan Carlos <notifications@github.com> wrote:
>+1
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pygrn/ideesxerrades/issues/5#issuecomment-313236747

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by XaviTorello** [comment]
Tanquem issue! Seleccionada per la sessió del dia 12/07/17

Gràcies @jbagot
