### ISSUE TITLE
Testing amb PyTest

### ISSUE THREAD

**Issue by oriolj** [pygrn/xerrades#51]
### Títol de la proposta

Tipus de la proposta:
- [x] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Pytest és un framework de testing per python, busca ser més pythonic que el unittest que porta python integrat (massa influenciat per JAVA).

La seva sintaxi es senzilla i directe, i escala fins casos molt complexos.

Hauria de preparar-ho millor, però crec que alguns punts a tractar interessants podrien ser:

- Test basic
- conftest
- Fixtures
- Integració amb flask, django...
- Markers
- unit, integracio i funcionals
- tools extra (sugar, faker, factoryboy, hypothesis, cov)

1-2h

TAGS: `testing, pytest, test`

**Comment by victormartingarcia** [comment]
Molt interessant @oriolj !

**Comment by manelclos** [comment]
Si necessites ajuda estic disponible al 200% :D

**Comment by XaviTorello** [comment]
Fa molt bona pinta :)! Thxs @oriolj :beer:

**Comment by oriolj** [comment]
> Si necessites ajuda estic disponible al 200% :D

genial, si acabem decidint fer la xerrada i possem data, podem fer-nos un planning!

**Comment by ytturi** [comment]
Crec que seria interessant mencionar compatibilitat/migració desde unittest

**Comment by XaviTorello** [comment]
Seleccionada pel proper dj 24/10! Gràcies @oriolj i @manelclos
