### ISSUE TITLE
Sessió sobre Infraestructura com a Codi

### ISSUE THREAD

**Issue by eduherraiz** [pygrn/xerrades#56]
### Taller de Infraestructura com a Codi

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Hola, som n'Edu Herraiz de Mallorca, enginyer de sistemes a apsl.net.
M'agradaria introduïr-vos la meva visió de les eines d'alt nivell de Infraestructura com a codi (IaC), fer un repàs de les mes empleades i casos pràctics aplicats.

Duració: 1h

TAGS: `iac, terraform, saltstack, puppet, chef, ansible, docker`

**Comment by XaviTorello** [comment]
Genial! Fa molt bona pinta, gràcies @eduherraiz :beers:

Parlem per planificar-la :)

**Comment by apslsistemas** [comment]
Genial! Ja me direu.
Sa meva idea es fer una introducció general sense entrar amb tot detall de les eines, per despres poder fer debat i que tots poguem compartir les nostres experiències.

**Comment by eduherraiz** [comment]
Genial! Ja me direu.
Sa meva idea es fer una introducció general sense entrar amb tot detall de les eines, per despres poder fer debat i que tots poguem compartir les nostres experiències.

**Comment by XaviTorello** [comment]
Gràcies @eduherraiz, xerrada seleccionada per la propera sessió (19/03/2020) :beers:
