### ISSUE TITLE
[Xerrada] Python Data Science

### ISSUE THREAD

**Issue by victormartingarcia** [pygrn/xerrades#6]
Python Data Science

- [x] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Estic treballant amb projectes de data science i machine learning. L'eina per excelència es python amb les llibreríes pandas, numpy, sklearn, etc., i m'agradaría fer una petita introducció.

Una forma molt bona d'aprendre es participant en una de les competicions de datascience de [kaggle.com](https://www.kaggle.com/) ([recentment adquirit per google](http://blog.kaggle.com/2017/03/08/kaggle-joins-google-cloud/)).

La meva idea es fer una sessió pràctica de com participar en la [competició d'introducció Titanic](https://www.kaggle.com/c/titanic) on es demana aplicar intel.ligència artifical per predict quins passatgers van sobreviure a la catàstrofe del titànic.

**Comment by guilleJB** [comment]
:+1:

**Comment by jccamel** [comment]
+1

**Comment by XaviTorello** [comment]
Tanquem issue! Seleccionada per la sessió del dia 18/10/17

Gràcies @victormartingarcia
