### ISSUE TITLE
[Xerrada] FastAPI

### ISSUE THREAD

**Issue by jbagot** [pygrn/xerrades#62]
### FastAPI

Tipus de la proposta:
- [x] Vull proposar un tema interessant
- [x] Vull fer una xerrada

[FastAPI](https://fastapi.tiangolo.com/) és un dels frameworks web de python que més està creixent, està basat en [Starlette](https://www.starlette.io/) i és un framework totalment asíncron d'arrel, que et proporciona documentació de l'API automàticament, té schemas de [pydantic](https://pydantic-docs.helpmanual.io/) per validar les dades de la API, funciona amb anotacions de python.  

La podria fer jo però sincerament no tinc molta experiència, si algú s'anima el puc ajudar o la podem fer plegats si ho necessita.

Duració: 1h

TAGS: `fastapi`, `starlette`, `pydantic`, `async`, `web framework`, `python`

**Comment by XaviTorello** [comment]
Seleccionada per la sessió del dia 26/05/22, gràcies @jbagot @toniGrabulosa :beers:

https://www.meetup.com/PythonGirona/events/285888074
