### ISSUE TITLE
[Xerrada] Dataframes en Python más allá de pandas

### ISSUE THREAD

**Issue by astrojuanlu** [pygrn/xerrades#65]
### Dataframes en Python más allá de pandas

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

La biblioteca pandas ha sido uno de los factores decisivos para el crecimiento de Python en la década pasada dentro de la industria del análisis de datos y continúa ayudando a data scientists a resolver problemas 15 años después de su creación. Gracias a su éxito, ahora hay varios proyectos open-source que afirman mejorar pandas de diversas maneras, ya sea llevándolo a un entorno distribuido (Dask), acelerando su rendimiento con cambios mínimos (Modin), u ofrciendo una API ligeramente distinta que resuelve alguna de sus limitaciones (Polars, Vaex).

Durante la charla

1. Haremos una breve introducción a pandas, hablaremos de su importancia, y señalaremos algunas de sus limitaciones
2. Enumeraremos algunas de sus alternativas y las clasificaremos (pandas-like o diferente, nodo único vs distribuido)
3. Presentaremos estas bibliotecas mostrando fragmentos de código, hablaremos de sus puntos fuertes, y visualizaremos la dependencia entre ellas

Al final de la charla la audiencia tendrá más información de cómo algunas de las alternativas modernas a pandas encajan dentro del ecosistema, entenderá cuáles proveen un camino para migrar más sencillo, y estará más preparada para juzgar cuál usar para próximos proyectos.

Conocimientos básicos de pandas ayudarán a entender el resto de la presentación.

Duració estimada: 30 minutos a 1 hora

TAGS: `pandas, dataframes, dask, vaex, modin, polars`

**Comment by XaviTorello** [comment]
Gracias @astrojuanlu, seleccionada para este 30/06! 🍻

**Comment by astrojuanlu** [comment]
¡Hecha la charla! Los materiales están en https://github.com/astrojuanlu/talk-dataframes (y la versión renovada, centrándose solo en Polars, en https://github.com/astrojuanlu/talk-polars). Espero poder subir otro día :heart:
