### ISSUE TITLE
[Xerrada] ¿Es un pájaro? ¿Es un avión? Acelerando código con numba

### ISSUE THREAD

**Issue by astrojuanlu** [pygrn/xerrades#66]
### ¿Es un pájaro? ¿Es un avión? Acelerando código con numba

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Tenemos suerte de tener soluciones muy variadas para hacer nuestro código Python más rápido: desde escribir parte del código en lenguajes compilados (NumPy, pandas) a alterar la sintaxis del lenguaje para hacerla más digerible a los compiladores (Cython) pasando por usar un subconjunto del lenguaje que pueda ser acelerado (numba, mypyc), y muchas más. Sin embargo, cada una de estas opciones tiene sus pros y sus contras, y no hay una solución mágica a todos nuestros problemas de rendimiento.

En esta charla vamos a enfocarnos en numba, el proyecto que elegí para acelerar los algoritmos de mi biblioteca de astrodinámica en Python, poliastro. numba compila código Python al vuelo usando LLVM, acelerando el rendimiento de manera bastante notable y con muy poco esfuerzo. numba es perfecto para código limitado por CPU (_CPU-bound_), puesto que para código limitado por E/S (_IO-bound_) otras estrategias como la concurrencia son más efectivas. Mencionaremos las GPUs solo de pasada.

Duració estimada: 30 minutos a 1 hora

TAGS: `rendimiento, numba, llvm`

**Comment by jbagot** [comment]
Aquesta xerrada ja es va fer al 2023. Tanco la issue.
