### ISSUE TITLE
[Xerrada] Programació professional en python

### ISSUE THREAD

**Issue by jsoucheiron** [pygrn/xerrades#67]
### Programació professional en python

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

La idea és parlar de com després de cometre pràcticament tots els errors que es poden cometre com a programador, he arribat a un conjunt de bones pràctiques, com gestionar PRs, dependencies, organitzar codi, etc. que et poden ajudar a ser un millor professional del codi.

Duració estimada: 30 mins

**Comment by XaviTorello** [comment]
Mola, mola! Serà una sessió molt interessant!!! Gràcies @jsoucheiron

**Comment by ecarreras** [comment]
Feta el 18/04/2023 https://meetu.ps/e/LX3D7/yB0tf/i
