### ISSUE TITLE
[Xerrada] Introducció a Airflow

### ISSUE THREAD

**Issue by oriolpiera** [pygrn/xerrades#69]
### Airflow, control de l'automatitzant de tasques recurrents

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Introducció a [Airflow](https://airflow.apache.org/) i com podem fer el nostre primer pipeline. Aquesta la xerrada la faria en @pauboixsom

Duració estimada: 30 min

TAGS: `airflow, schedule, workflow`

**Comment by jbagot** [comment]
Aquesta xerrada es va fer a la segona festa del software de girona a l'octubre del 2022
