### ISSUE TITLE
[Tema] React

### ISSUE THREAD

**Issue by victormartingarcia** [pygrn/xerrades#7]
React

Tipus de la proposta:
- [x] Vull proposar un tema interessant
- [ ] Vull fer una xerrada

Tot i no ser estrictament python, estaria molt bé que algú amb experiència expliqués els fonaments de React/React native, pros-contres, etc., :)

**Comment by francescarpi** [comment]
Jo m'ofereixo per la de React enfocat al Web.

**Comment by XaviTorello** [comment]
Genial @francescarpi 😄 

Si no et sap greu obre una issue nova proposant la xerrada referenciant aquesta s.u.p
