### ISSUE TITLE
[Xerrada] Django + Quasar(Vue)

### ISSUE THREAD

**Issue by xdiume** [pygrn/xerrades#70]
### Projectes amb Django i Quasar (Vue)

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Exemple de com plantejar un projecte amb Django utilitzant Quasar (Vue) per a la part gràfica, de components i javascript.

Duració estimada: 1h

TAGS: `Django, Quasar, Vue, JS`

**Comment by XaviTorello** [comment]
Seleccionada per l'01/12, moltes gràcies @xdiume! 🍻

**Comment by jbagot** [comment]
Aquesta xerrada es va fer el desembre del 2022
