### ISSUE TITLE
Machine Learning com a servei

### ISSUE THREAD

**Issue by mmerce** [pygrn/xerrades#73]
### Machine Learning com a servei

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [X] Vull fer una xerrada

Xerrada introductòria a l'Aprenentatge automàtic (Machine Learning) i com prendre decisions usant els models que genera. Farem un primer model utilitzant el servei que BigML té disponible al núvol (https://bigml.com) i veurem com mesurar la seva fiabilitat.

Nivell de la xerrada: Iniciació. No calen coneixements de programació previs, però si l'audiència té coneixements de Python podrem comentar com manegar els models creats i utilitzar-los per fer prediccions.

Duració estimada: 45'

TAGS: `Machine Learning, Presa de decisions, SaaS `

**Comment by ecarreras** [comment]
Moltes gràcies!

**Comment by ecarreras** [comment]
Feta el dia 19/09/2024: https://www.meetup.com/es-ES/pythongirona/events/303387625/
