### ISSUE TITLE
Xerrada sobre GraphQL i maduixes

### ISSUE THREAD

**Issue by eudago** [pygrn/xerrades#74]
### Xerrada sobre GraphQL i maduixes

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [x] Vull fer una xerrada

Explicarem en profunditat que és, com funciona, avantatges i desavantatges versus API Rest. 
Apendrem a crear un servidor amb GraphQL utilitzant la llibreria [strawberry](https://strawberry.rocks/).
Xerrada conjunta amb [rbetancourt27](https://github.com/rbetancourt27)

Duració estimada: 30-45 min

TAGS: `python, graphql, fastapi`

**Comment by XaviTorello** [comment]
Mola!!! Gràcies @eudago @rbetancourt27

Quan creieu que la podríem fer aprox?

**Comment by rbetancourt27** [comment]
> Mola!!! Gràcies @eudago @rbetancourt27
> 
> Quan creieu que la podríem fer aprox?

Hola @XaviTorello ! Nosaltres considerem que entre principis i mitjans de març està la nostra data ideal. Amb el pas dels dies podríem anar concretant. Com tenim la disponibilitat?

**Comment by XaviTorello** [comment]
Pyrfecte! Quan tingueu news aviseu aquí mateix i mirem de planificar-la. Merci cracks!

**Comment by jbagot** [comment]
Aquesta xerrada es va fer el 14/03/2024, tanco la issue
