### ISSUE TITLE
Python + Terraform per administrar 74 comptes a AWS

### ISSUE THREAD

**Issue by joelperez98** [pygrn/xerrades#75]
### Python + Terraform per administrar 74 comptes a AWS

Tipus de la proposta:
- [ ] Vull proposar un tema interessant
- [X] Vull fer una xerrada

Per cada compte de AWS que teníem, es creava un repositori de git amb tot el codi de Terraform que administrava els recursos propis del compte. Per exemple:
- Recursos de xarxa (Nat gateway, VPC)
- Polítiques d'accés i seguretat (Permission Sets, rols)

Entre d'altres. Com podeu imaginar, tot aquest codi estava repetit en els repositoris dels diferents comptes.
El problema va sorgir quan vam voler fer modificacions en aquests mòduls de Terraform. Per exemple, vam voler reduir els NAT Gateways de 3 per compte a 1. Això implica fer canvis a 74 repositoris. Una feina innecessària, no creieu?

En aquesta xerrada vull explicar com vam solucionar aquest problema utilitzant la programació, Python en aquest cas. Si bé es tracta d'un problema bastant ad hoc, és un bon exemple de com podem administrar el Cloud amb propgramari propi. A més, vull esmentar altres problemes que hem solucionat amb software propi.

Duració estimada: 30 minuts

TAGS: `Python, Terraform, AWS, Gitlab CI`

**Comment by ecarreras** [comment]
Moltes gràcies!! 🙌🏻🙌🏻🙌🏻

**Comment by XaviTorello** [comment]
Mola mola! Merci @joelperez98

**Comment by joelperez98** [comment]
Tanco la issue per motius personals varis. Igualment, segur que em surgirà alguna altra idea.
